### ISSUE TITLE
Validating Salesforce connection does not seem right.

### ISSUE THREAD

**Issue by chirino** [redhat-ipaas/ipaas-rest#339]
Got a validation error on an OK response.

<img width="791" alt="red_hat_ipaas" src="https://cloud.githubusercontent.com/assets/103255/25410162/2a900838-29e3-11e7-8d3c-6a6cca7dd017.png">

**Comment by zregvart** [comment]
According to [AbstractClientBase.java#L150](https://github.com/apache/camel/blob/master/components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/internal/client/AbstractClientBase.java#L150) Jetty threw an exception. Can you set Jetty logger to debug so it's visible? Or is there a SalesforceException logged somewhere?

**Comment by rhuss** [comment]
Let me check that. There has been some slight changes in the upstream Verifier API which I need to verify. will work on this today.

**Comment by lburgazzoli** [comment]
@rhuss if you need any help with camel ping me

**Comment by zregvart** [comment]
I can't reproduce this, I was struggling to find the exact screen (the SObject Id Name was removed in #338), but this scenario (username-password) works OK with my Salesforce organization and user.

Salesforce is quite picky about letting anyone in, few things of note:
- relax IP setting should be set on the Connected app OAuth
- Permitted Users policy should be: All users may self authorize
- if using security tokens, the security token must be appended to the password (password becomes `password || security token`)

**Comment by rhuss** [comment]
Just verified that it works for me, too.

However, I find the UI a bit confusing: I would expect User Name and Password to be close together, with User Name before password. Also, the hints within the text input fields are too long. I think a tooltip would be more appropriate here. The ice of the cake would be if the UI logic could ensure that either refreshToken or (user, password) can be entered by disabling fields when one is added. But I guess that's too much (because this info is probably not available at the point)

![image](https://cloud.githubusercontent.com/assets/99080/25429293/c606b1d2-2a78-11e7-9adb-504027c10df8.png)

**Comment by rhuss** [comment]
Ok, I didn't tried it with username / password (and have probably still an old version without SObject ID).

**Comment by chirino** [comment]
Actually SObjectID should not have been there. you have the latest version.

**Comment by zregvart** [comment]
As long as we're throwing screenshots, here is mine

![selection_303](https://cloud.githubusercontent.com/assets/1306050/25441147/b08aa7e0-2aa1-11e7-9a2f-3b1184177659.png)

**Comment by chirino** [comment]
I've not been able to reproduce the error.  Closing out.
