### ISSUE TITLE
Wrong desired state when deactivating integration ?

### ISSUE THREAD

**Issue by rhuss** [redhat-ipaas/ipaas-rest#343]
[This](https://github.com/rhuss/ipaas-rest/blob/8d1d6030be55cea310e20f9cead70d7acbfd7149/rest/src/main/java/com/redhat/ipaas/rest/v1/handler/integration/IntegrationHandler.java#L62-L62) looks so obvious wrong that I wonder whether it is intentional (and it was updated 5 days ago). If so, a comment would be nice ;-)

**Comment by jimmidyson** [comment]
From an unreviewed PR #325 merged including changes that are unrelated to the pr message... Yay!

I would also rather have done activate by patch request to integration/id or subresource of integration/id/desiredStatus to keep rest API noun based rather than verb based.

Now that we have summit almost out of the way, I'd like to review the rest API, models, etc but at least we can quickly fix this issue.

**Comment by rhuss** [comment]
Agreed with doing a thorough review of the API (and the domain model) after summit.

To be fair, #325 did only a reformatting of the code, including the bug which was introduced earlier ;-)

I will do the quick fix.

**Comment by jimmidyson** [comment]
Oops yeah didn't notice that it was just a reformatting... I take back my disapproval!

**Comment by rhuss** [comment]
Fixed via #344
