### ISSUE TITLE
pick a default expression language

### ISSUE THREAD

**Issue by jstrachan** [redhat-ipaas/ipaas-rest#51]
we need a default OOTB expression language to use for steps like Flow, Choice, Split etc.

Which should we pick? I was thinking of JSONPath but thats not awesome for predicates. e.g. to filter on the name property of some JSON its: `$.[?(@.name == 'James')]` e.g. see this example https://github.com/funktionio/funktion-connectors/blob/master/funktion-runtime/src/test/java/io/fabric8/funktion/runtime/steps/FilterTest.java#L75-L75

We maybe need to make a new Language for Camel thats simple to type and grok (e.g. `foo.bar > 123` or `foo[2].name == 'cheese'`

Anyone got a preference? Here's whats available today: http://camel.apache.org/languages.html

I noticed in a doc reference to `cloudforms language` but I've no idea what that is - any links?

**Comment by jstrachan** [comment]
wonder if we can try extend JSONPAth to make expressions possible? e.g `$.name == “James”` isn't too bad?

**Comment by KurtStam** [comment]
To what user is this expression language going to be exposed to?

**Comment by jstrachan** [comment]
its whatever the citizen developer edits in the Filter / Choice / Split step editor

**Comment by jimmidyson** [comment]
I think we should take this issue out into a separate repo where we can define Flow language a bit better, including deciding this, & provide libraries for it. Will help with upstreaming it too in future if we decide to do so. What do you think?

**Comment by jstrachan** [comment]
sure - still no clue if an existing language could do the job or if we need to make a new one or whatever . Certainly if a new language is required we should spin it up in a separate repo (though it'd be easier to productise as a module inside funktion-connectors as its just a jar  - but am easy either way really)

**Comment by jstrachan** [comment]
yeah - the option is we let users enter a `name == "james"` type string; or we create a predicate & expression creator UI. The latter is harder but avoids the expression problem completely. 

It shouldn't be too hard though; e.g. to navigate through an example message, select the bit you want and type in an operation (== > < etc) and a value for many expressions

**Comment by jstrachan** [comment]
the main issue is what if the data doesn't contain the shaped data that you need to create the expression; sometimes its just easier to type `foo.bar > 12" or something

**Comment by KurtStam** [comment]
We should honestly look at Scratch.

On Jan 12, 2017, at 12:14, James Strachan <notifications@github.com> wrote:

the main issue is what if the data doesn't contain the shaped data that you
need to create the expression; sometimes its just easier to type `foo.bar >
12" or something

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/redhat-ipaas/ipaas-api-java/issues/51#issuecomment-272223400>,
or mute the thread

**Comment by KurtStam** [comment]
http://scratched.gse.harvard.edu/sites/default/files/computational_concepts_supported_in_scratch_2017_0.pdf

On Jan 12, 2017, at 13:36, Kurt Stam <kstam@redhat.com> wrote:

We should honestly look at Scratch.

On Jan 12, 2017, at 12:14, James Strachan <notifications@github.com> wrote:

the main issue is what if the data doesn't contain the shaped data that you
need to create the expression; sometimes its just easier to type `foo.bar >
12" or something

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/redhat-ipaas/ipaas-api-java/issues/51#issuecomment-272223400>,
or mute the thread

**Comment by davsclaus** [comment]
We have made camel-jsonpath easier with 2.19 where you can do easier filters
https://github.com/apache/camel/blob/master/components/camel-jsonpath/src/main/docs/jsonpath-language.adoc#easy-syntax

**Comment by jstrachan** [comment]
@davsclaus thats super awesome - thanks!!!
